# Identificador de esta instancia del worker
worker.id=worker-default

# Dirección HTTP del Coordinator
coordinator.url=http://localhost:8080

# Puerto HTTP propio del proceso Worker para no chocar con el Coordinator
server.port=8081
